# Generated by Django 5.0.6 on 2025-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetsettings',
            name='budget_categories',
            field=models.JSONField(default=list),
        ),
    ]
