# Generated by Django 5.0.6 on 2025-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsettings',
            name='budget_categories',
        ),
        migrations.AddField(
            model_name='budgetsettings',
            name='categories',
            field=models.ManyToManyField(null=True, to='users.category'),
        ),
    ]
