# Generated by Django 5.0.6 on 2025-12-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_budgetsettings_budget_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetsettings',
            name='categories',
            field=models.ManyToManyField(blank=True, to='users.category'),
        ),
    ]
