# Generated by Django 5.2 on 2025-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expenses', 'Expenses'), ('income', 'Income')], max_length=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('debit', 'Debit Card'), ('credit', 'Credit Card'), ('bank', 'Bank Transfer')], max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipt/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
