# Generated by Django 5.0.6 on 2025-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipt/%Y/%m/'),
        ),
    ]
